app = 'd--j'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/"
    protocol = "http"
    timeout = 2000
    tls_skip_verify = false

[[services]]
  internal_port = 1935
  protocol = "tcp"
  
  [[services.ports]]
    port = 1935
    handlers = ["tcp"]

[[services]]
  internal_port = 554
  protocol = "tcp"
  
  [[services.ports]]
    port = 554
    handlers = ["tcp"]

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048  # Flussonic يحتاج 2GB على الأقل

[mounts]
  source = "flussonic_data"
  destination = "/var/www"
